# Generated by Django 3.1.5 on 2021-01-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_auto_20210118_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='logo',
            field=models.ImageField(blank=True, default='logos_restaurantes/hamburger.jpg', null=True, upload_to='logos_restaurantes/'),
        ),
    ]
